<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\AccueilController::index'], [], [['text', '/']], [], [], []],
    'booking' => [[], ['_controller' => 'App\\Controller\\BookingController::reserver'], [], [['text', '/booking']], [], [], []],
    'bookings' => [[], ['_controller' => 'App\\Controller\\BookingController::reservations'], [], [['text', '/bookings']], [], [], []],
    'booking_annuler' => [['id'], ['_controller' => 'App\\Controller\\BookingController::annuler'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/booking/annuler']], [], [], []],
    'booking_confirmer' => [['id'], ['_controller' => 'App\\Controller\\BookingController::confirmer'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/booking/confirmer']], [], [], []],
    'service_list' => [[], ['_controller' => 'App\\Controller\\ServiceController::list'], [], [['text', '/services']], [], [], []],
    'App\Controller\AccueilController::index' => [[], ['_controller' => 'App\\Controller\\AccueilController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\BookingController::reserver' => [[], ['_controller' => 'App\\Controller\\BookingController::reserver'], [], [['text', '/booking']], [], [], []],
    'App\Controller\BookingController::reservations' => [[], ['_controller' => 'App\\Controller\\BookingController::reservations'], [], [['text', '/bookings']], [], [], []],
    'App\Controller\BookingController::annuler' => [['id'], ['_controller' => 'App\\Controller\\BookingController::annuler'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/booking/annuler']], [], [], []],
    'App\Controller\BookingController::confirmer' => [['id'], ['_controller' => 'App\\Controller\\BookingController::confirmer'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/booking/confirmer']], [], [], []],
    'App\Controller\ServiceController::list' => [[], ['_controller' => 'App\\Controller\\ServiceController::list'], [], [['text', '/services']], [], [], []],
];
